<?php
/**
 * @file
 * Code for the ldlm_formation feature.
 */

include_once 'ldlm_formation.features.inc';


/**
 * Implements hook_node_view_alter().
 */
function ldlm_formation_node_view_alter(&$build) {
  //dpm($build);
  $link = '';
  $path_alias = drupal_get_path_alias('node/'.$build['#node']->vid);
  
  
  if ($build['#bundle'] == 'formation' && $build['#view_mode'] == 'full') {
    $link = isset($build['field_preinscription_scolaire']);
    if($link) {
      $build['field_preinscription_scolaire'][0]['#markup'] = 
         '<a href="/'.$path_alias.'?formation='.$build['#node']->title.'#block-webform-client-block-4">Faire une demande de pré-inscription</a>';
      
    }
    $link = isset($build['field_demande_entretien']);
    if($link) {
      $build['field_demande_entretien'][0]['#markup'] = 
         '<a href="/'.$path_alias.'?formation='.$build['#node']->title.'#block-webform-client-block-6">Demander un entretien</a>';
      
    }
    $link = isset($build['field_portes_ouvertes']);
    if($link) {
      $build['field_portes_ouvertes'][0]['#markup'] = 
         '<a href="/'.$path_alias.'?formation='.$build['#node']->title.'#block-webform-client-block-7">S\'inscrire à la journée Portes Ouvertes</a>';
      
    }
    $link = isset($build['field_documentation']);
    if($link) {
      $build['field_documentation'][0]['#markup'] = 
         '<a href="/'.$path_alias.'?formation='.$build['#node']->title.'#block-webform-client-block-8">Revevoir une documentation</a>';
      
    }
    $link = isset($build['field_remplir_formulaire']) && $build['field_remplir_formulaire']['#items'][0]['value'];
    //dpm($build['field_remplir_formulaire']);
    if($link) {
      $build['field_remplir_formulaire'][0]['#markup'] = 
         '<a href="/'.$path_alias.'?formation='.$build['#node']->title.'#block-webform-client-block-9">Remplir le formulaire</a>';
      
    }
    
  }
}